import { StyleSheet } from "@react-pdf/renderer";

export const reportStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#333",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderBottom: "2px solid #1e40af",
    paddingBottom: 15,
  },
  logo: {
    width: 120,
    height: 50,
    objectFit: "contain",
  },
  headerDate: {
    fontSize: 9,
    color: "#666",
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1e40af",
    marginBottom: 20,
    textAlign: "center",
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1e40af",
    marginBottom: 10,
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: 5,
  },
  row: {
    flexDirection: "row",
    marginBottom: 4,
  },
  label: {
    width: 130,
    fontWeight: "bold",
    color: "#555",
    fontSize: 10,
  },
  value: {
    flex: 1,
    fontSize: 10,
  },
  kpiRow: {
    flexDirection: "row",
    gap: 20,
    marginBottom: 15,
  },
  kpiCard: {
    flex: 1,
    backgroundColor: "#f0f4ff",
    borderRadius: 4,
    padding: 12,
    border: "1px solid #c7d2fe",
  },
  kpiLabel: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#1e40af",
    marginBottom: 4,
  },
  kpiValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 2,
  },
  kpiDesc: {
    fontSize: 8,
    color: "#6b7280",
  },
  table: {
    marginTop: 8,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    padding: 8,
    fontWeight: "bold",
    fontSize: 9,
  },
  tableRow: {
    flexDirection: "row",
    padding: 8,
    borderBottom: "1px solid #e5e7eb",
  },
  tableRowAlt: {
    flexDirection: "row",
    padding: 8,
    borderBottom: "1px solid #e5e7eb",
    backgroundColor: "#fafafa",
  },
  colMes: { width: "30%", fontSize: 9 },
  colPrevisto: { width: "23%", textAlign: "right", fontSize: 9 },
  colReal: { width: "23%", textAlign: "right", fontSize: 9 },
  colVariacao: { width: "24%", textAlign: "right", fontSize: 9 },
  colTipo: { width: "35%", fontSize: 9 },
  colValPrev: { width: "32%", textAlign: "right", fontSize: 9 },
  colValReal: { width: "33%", textAlign: "right", fontSize: 9 },
  totalRow: {
    flexDirection: "row",
    padding: 8,
    backgroundColor: "#e5e7eb",
    fontWeight: "bold",
  },
  resultSection: {
    marginTop: 15,
    padding: 12,
    backgroundColor: "#f0f4ff",
    borderRadius: 4,
    border: "1px solid #c7d2fe",
  },
  resultRow: {
    flexDirection: "row",
    marginBottom: 5,
  },
  resultLabel: {
    width: 150,
    fontWeight: "bold",
    color: "#374151",
    fontSize: 11,
  },
  resultValue: {
    flex: 1,
    fontSize: 11,
    fontWeight: "bold",
    color: "#1e40af",
  },
  observations: {
    marginTop: 15,
    padding: 10,
    backgroundColor: "#f9fafb",
    borderRadius: 4,
    fontSize: 9,
    lineHeight: 1.6,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
    borderTop: "1px solid #e5e7eb",
    paddingTop: 10,
  },
});
