// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsrkdqtvwsbzkjqmzqfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcmtkcXR2d3NiemtqcW16cWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjUzMTksImV4cCI6MjA1NzY0MTMxOX0.rK3kMtas2r-LIC5jVztJtd7npqbgt8oPuVWe_uD8K_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});